Fixed Requrie MRN patient setting - see issue #70
senaite/senaite.patient pull request #71
Opened 2023-05-12 16:14 UTC by mikejmets

## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.patient/issues/70

## Current behavior before PR

## Desired behavior after PR is merged

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2023-05-12 16:16 UTC, mikejmets commented
I set this to Draft because the tests I created fail. Namely, when the Require MRN setting is True and I create a Patient with no MRN value, the patient is created. My test expects it to fail. Am I wrong?

2023-05-14 20:09 UTC, ramonski requested changes

2023-05-14 20:09 UTC, ramonski commented on src/senaite/patient/tests/doctests/Patient.rst
> +    <Patient at /plone/patients/P000002>
The validator is not called when the field is set. It is only called when the form is submitted, e.g. like `processForm` in AT but it is called `applyValue` here:
https://github.com/zopefoundation/z3c.form/blob/master/src/z3c/form/widget.py#L404

Therefore, this test will always pass unless you do the same validation dance inside the custom filed setter.

2023-05-15 13:37 UTC, mikejmets commented on src/senaite/patient/adapters/listing.py
> +            patient = self.get_patient_by_id(sample_patient_id)
Done

2023-05-15 21:02 UTC, ramonski commented
Thanks for the fix Mike. Would you mind to add a Changelog entry, then we can merge it.

2023-05-16 08:36 UTC, mikejmets commented
Changelog updated

2023-05-16 14:17 UTC, ramonski approved these changes

2023-05-16 14:17 UTC, merged